/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdeptosRouteImport } from './routes/adeptos'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as EquipamentosRouteImport } from './routes/equipamentos'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as PersonalizarRouteImport } from './routes/personalizar'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdeptosRoute = AdeptosRouteImport.update({
  id: '/adeptos',
  path: '/adeptos',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosRoute = EquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizarRoute = PersonalizarRouteImport.update({
  id: '/personalizar',
  path: '/personalizar',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adeptos': typeof AdeptosRoute
  '/carrinho': typeof CarrinhoRoute
  '/contactos': typeof ContactosRoute
  '/equipamentos': typeof EquipamentosRoute
  '/loja': typeof LojaRoute
  '/personalizar': typeof PersonalizarRoute
  '/portfolio': typeof PortfolioRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adeptos': typeof AdeptosRoute
  '/carrinho': typeof CarrinhoRoute
  '/contactos': typeof ContactosRoute
  '/equipamentos': typeof EquipamentosRoute
  '/loja': typeof LojaRoute
  '/personalizar': typeof PersonalizarRoute
  '/portfolio': typeof PortfolioRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adeptos': typeof AdeptosRoute
  '/carrinho': typeof CarrinhoRoute
  '/contactos': typeof ContactosRoute
  '/equipamentos': typeof EquipamentosRoute
  '/loja': typeof LojaRoute
  '/personalizar': typeof PersonalizarRoute
  '/portfolio': typeof PortfolioRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adeptos'
    | '/carrinho'
    | '/contactos'
    | '/equipamentos'
    | '/loja'
    | '/personalizar'
    | '/portfolio'
    | '/produto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adeptos'
    | '/carrinho'
    | '/contactos'
    | '/equipamentos'
    | '/loja'
    | '/personalizar'
    | '/portfolio'
    | '/produto/$slug'
  id:
    | '__root__'
    | '/'
    | '/adeptos'
    | '/carrinho'
    | '/contactos'
    | '/equipamentos'
    | '/loja'
    | '/personalizar'
    | '/portfolio'
    | '/produto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdeptosRoute: typeof AdeptosRoute
  CarrinhoRoute: typeof CarrinhoRoute
  ContactosRoute: typeof ContactosRoute
  EquipamentosRoute: typeof EquipamentosRoute
  LojaRoute: typeof LojaRoute
  PersonalizarRoute: typeof PersonalizarRoute
  PortfolioRoute: typeof PortfolioRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adeptos': {
      id: '/adeptos'
      path: '/adeptos'
      fullPath: '/adeptos'
      preLoaderRoute: typeof AdeptosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos': {
      id: '/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof EquipamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalizar': {
      id: '/personalizar'
      path: '/personalizar'
      fullPath: '/personalizar'
      preLoaderRoute: typeof PersonalizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdeptosRoute: AdeptosRoute,
  CarrinhoRoute: CarrinhoRoute,
  ContactosRoute: ContactosRoute,
  EquipamentosRoute: EquipamentosRoute,
  LojaRoute: LojaRoute,
  PersonalizarRoute: PersonalizarRoute,
  PortfolioRoute: PortfolioRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
